name: flutter_main
description: "A new Flutter module project."

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  flutter_screenutil: ^5.5.4

  cached_network_image: ^3.3.1 #网络图片缓存

  #滑动切换按钮
  slide_switcher: ^1.1.2

  # 网络库
  dio: ^5.4.3+1
  dio_cookie_manager: ^3.1.1
  pretty_dio_logger: ^1.3.1

  # 本地存储
  shared_preferences: ^2.3.2

  # 状态管理
  # https://pub-web.flutter-io.cn/packages/provider/example
  provider: ^6.1.2
  # https://pub.dev/packages/get/example
  get: ^4.6.6

  # 上拉加载 下拉刷新
  liquid_pull_to_refresh: ^3.0.1
  #https://github.com/xuelongqy/flutter_easy_refresh/blob/v3/README_CN.md
  easy_refresh: ^3.4.0

  # 底部导航
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.0
  font_awesome_flutter: 10.1.0

  # 底部导航
  persistent_bottom_nav_bar: any

  flutter_easyloading: ^3.0.5
  event_bus: ^2.0.0
  flutter_downloader: ^1.11.8

  #  connectivity: ^3.0.6

  # WebView 库
  # https://pub.dev/packages/webview_flutter/example
  webview_flutter: ^4.9.0

  # 封装
  logger: ^2.4.0

#  permission_handler: ^11.3.1
  text_scroll: ^0.2.0
  bottom_picker: ^2.8.0
  ##flv视频播放器
#  fijkplayer: ^0.11.0
  ##aes加密
  encrypt: ^5.0.3
  convert: ^3.1.1
  json_annotation: ^4.9.0


  # web socket 插件
  web_socket_channel: ^3.0.1

  # web socket 插件
  flutter_js: ^0.8.1

  # https://pub.dev/packages/fluttertoast/example
  fluttertoast: ^8.2.8

  # https://pub.dev/packages/json_serializable/example
  json_serializable: ^6.8.0
  connectivity_plus: ^6.0.5
  volume_controller: ^2.0.8
  flutter_svg: ^2.0.10+1
  flutter_smart_dialog: ^4.9.8+3
  lottie: ^3.1.2
  contained_tab_bar_view: ^0.8.0
  custom_sliding_segmented_control: ^1.8.3
  simple_animations: ^5.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

  # https://pub.dev/packages/json_serializable/example
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Besley
      fonts:
        - asset: assets/fonts/chip_Besley_Bold.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/loading.gif
    - assets/images/road/light/
    - assets/images/road/dark/
    - assets/images/modeSelect/
    - assets/images/modeSelect/dark/
    - assets/images/modeSelect/light/
    - assets/images/road/roadSetting/
    - assets/images/road/roadSetting/light/
    - assets/images/road/roadPaperIcon/
    - assets/images/road/roadPaperDirectIcon/
    - assets/images/road/roadPartIcon/cn/SmallRoad/
    - assets/images/road/roadPartIcon/cn/ZhuPanRoad/
    - assets/images/road/dark/
    - assets/images/road/light/
    - assets/images/common/dark/
    - assets/images/common/light/
    - assets/images/road/roadSetting/dark/
    - assets/images/tabbar/dark/
    - assets/images/tabbar/light/
    - assets/images/userProfile/
    - assets/images/userProfile/svgs/
    - assets/images/userProfile/light/
    - assets/images/userProfile/dark/
    - assets/images/userProfile/singleImgs/light/
    - assets/images/userProfile/singleImgs/dark/
    - assets/images/play/
    - assets/images/chips/
    - assets/js/test.js
    - assets/js/DataHandle.js
    - assets/json/
    - assets/images/playingCards/clubs/normal/
    - assets/images/playingCards/clubs/black/
    - assets/images/playingCards/diamonds/normal/
    - assets/images/playingCards/hearts/normal/
    - assets/images/playingCards/hearts/black/
    - assets/images/playingCards/spades/normal/
    - assets/images/playingCards/spades/black/
    - assets/images/play/icon_play_amount.png
    - assets/images/play/chat/
    - assets/images/play/chat/dark/
    - assets/images/play/chat/light/
    - assets/images/play/chat/chat_icon/
    - assets/images/play/chat/icon/
    - assets/images/userProfile/3.0x/arrow_bottom.png
    - assets/images/play/gema/dark/
    - assets/images/play/gema/light/
    - assets/images/goodRoad/light/
    - assets/images/goodRoad/dark/
    - assets/images/goodRoad/tag/
    - assets/images/goodRoad/cn/
    - assets/images/goodRoad/en/
    - assets/images/goodRoad/tc/
    - assets/images/goodRoad/tag/cn/
    - assets/images/goodRoad/tag/en/
    - assets/images/goodRoad/tag/tc/
    - assets/images/goodRoad/odds/
    - assets/images/goodRoad/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.dp.flutter_main
    iosBundleIdentifier: com.dp.flutterMain
